### ISSUE TITLE
[Bug]: Cannot Perform Deep Crawling When Crawl4AI is Running via Docker

### ISSUE THREAD

**Issue by QuangTQV** [unclecode/crawl4ai#1052]
### crawl4ai version

0.6.1

### Expected Behavior

Crawl4AI should perform deep crawling when using CrawlerRunConfig with a BFSDeepCrawlStrategy, even if the Crawl4AI server is running in a Docker container.
I expected it to crawl the root page, discover internal links, and then crawl those internal pages up to the specified depth.

### Current Behavior

When running Crawl4AI via Docker and using the Python SDK externally, no data is crawled beyond the root URL. results.success is always False and no markdown content is returned.

### Is this reproducible?

Yes

### Inputs Causing the Bug

```bash

```

### Steps to Reproduce

```bash

```

### Code snippets

```python
import asyncio
import os

from crawl4ai import (
    BrowserConfig,
    CacheMode,
    CrawlerRunConfig,
    DefaultMarkdownGenerator,
    PruningContentFilter,
)
from crawl4ai.deep_crawling import BFSDeepCrawlStrategy
from crawl4ai.docker_client import Crawl4aiDockerClient


async def main():
    # Load custom JS if needed
    browser_script_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "crawl4ai_browser_script.js")
    )
    js_code = None
    if os.path.exists(browser_script_path):
        with open(browser_script_path, "r", encoding="utf-8") as f:
            js_code = f.read()

    async with Crawl4aiDockerClient(
        base_url="http://localhost:11235",
        verbose=True,  # 🔁 Change from localhost if calling from another container
    ) as client:
        # If authentication is truly disabled in config.yml, you can skip this
        # Otherwise, uncomment below
        await client.authenticate("your@email.com")

        print("--- Running Deep Crawl (Streaming Mode) ---")

        crawler_config = CrawlerRunConfig(
            cache_mode=CacheMode.BYPASS,
            excluded_tags=["header", "footer", "nav"],
            remove_overlay_elements=True,
            exclude_external_links=True,
            exclude_social_media_links=True,
            scroll_delay=0.5,
            scan_full_page=True,
            page_timeout=18000000,
            js_code=js_code,
            stream=True,
            deep_crawl_strategy=BFSDeepCrawlStrategy(
                max_depth=2,
                include_external=False,
                max_pages=20,
            ),
            markdown_generator=DefaultMarkdownGenerator(
                content_filter=PruningContentFilter(
                    threshold=0.48,
                    threshold_type="fixed",
                    min_word_threshold=0,
                ),
                options={"ignore_links": True},
            ),
        )

        async for result in await client.crawl(
            ["https://www.dienmayxanh.com/"],
            browser_config=BrowserConfig(headless=True),
            crawler_config=crawler_config,
        ):
            print(f"\n✅ URL: {result.url}")
            print(f"Success: {result.success}")
            if result.markdown:
                print(result.markdown.raw_markdown[:300])  # Print first 300 chars
                internal_links: list[dict] = result.links.get("internal", [])
                print(f"Found {len(internal_links)} internal links")
            else:
                print("No markdown content found.")


if __name__ == "__main__":
    asyncio.run(main())
```

### OS

macOS

### Python version

3.10.12

**Comment by aravindkarnam** [comment]
I was able to reproduce the issue and error message is `"'async_generator' object has no attribute 'status_code'"`. This seems to be happening with stream=True and the issue is in the docker_client.

**Comment by aravindkarnam** [comment]
This issue is related to https://github.com/unclecode/crawl4ai/issues/1066

**Comment by peterkostadinov** [comment]
related to https://github.com/unclecode/crawl4ai/issues/1205

**Comment by ntohidi** [comment]
Fixed in the newest release, 0.7.6. please pull the latest image

**Comment by markwainwright** [comment]
@ntohidi I'm still seeing this issue on 0.7.6 and 0.7.7.

Steps to reproduce:

```sh
docker run -p 11235:11235 unclecode/crawl4ai:0.7.7
```

```sh
curl http://localhost:11235/crawl/stream -X POST -H "Content-Type: application/json" --data-raw '{
  "urls": ["https://example.com"],
  "crawler_config": {
    "type": "CrawlerRunConfig",
    "params": {
      "stream": true,
      "deep_crawl_strategy": {
        "type": "BFSDeepCrawlStrategy",
        "params": { "max_depth": 1, "max_pages": 5 }
      }
    }
  }
}'
```

Result (formatted):

```json
{
  "url": "https://example.com",
  "html": "",
  "fit_html": "<property object at 0xffffb70fb600>",
  "success": false,
  "cleaned_html": null,
  "media": {},
  "links": {},
  "downloaded_files": null,
  "js_execution_result": null,
  "screenshot": null,
  "pdf": null,
  "mhtml": null,
  "extracted_content": null,
  "metadata": {},
  "error_message": "'async_generator' object has no attribute 'status_code'",
  "session_id": null,
  "response_headers": null,
  "status_code": null,
  "ssl_certificate": null,
  "dispatch_result": {
    "task_id": "cebeccd3-6dcf-429c-a9c1-4b940768d176",
    "memory_usage": 0.0,
    "peak_memory": 0.0,
    "start_time": 1764628981.1355639,
    "end_time": 1764628981.1357234,
    "error_message": "'async_generator' object has no attribute 'status_code'"
  },
  "redirected_url": null,
  "network_requests": null,
  "console_messages": null,
  "tables": [],
  "server_memory_mb": 139.53125
}
{
  "status": "completed"
}
```

Docker container logs:

```
2025-12-01 23:01:33,807 - crawler_pool - INFO - 🆕 Creating new browser in cold pool (sig=5d49607c, mem=6.3%)
2025-12-01 23:01:33,967 - api - INFO - Streaming result for https://example.com
```

**Comment by mathews-cometchat** [comment]
@ntohidi @aravindkarnam @Ahmed-Tawfik94  This error still exists.

**Comment by dip497** [comment]
any updated regarding same ?

**Comment by Qbason** [comment]
Version 0.8 the same issue 😢 
Docker API + Deep crawling + Stream doesn't work -> "error_message": "'async_generator' object has no attribute 'status_code'",
I have tried even example from: 
[docker](https://github.com/unclecode/crawl4ai/tree/main/docs/examples/docker)
/demo_docker_api.py
method -> demo_deep_streaming
The same result.

It should be reopened @ntohidi

**Comment by amal5haji** [comment]
Same on latest docker image

**Comment by Daandeve** [comment]
+1 Having the same issue on the latest 0.8.0 version `"'list' object has no attribute 'status_code'"`

**Comment by Ahmed-Tawfik94** [comment]
# Issue 1052 Root Cause Report

## Observed Behavior

Two variants of the error occur depending on configuration:

### Variant 1: async_generator error (stream=True)
```
Error: "'async_generator' object has no attribute 'status_code'"
```
- Occurs when using deep crawl + `stream=True`
- This is what the original issue reporter experienced (v0.6.x)

### Variant 2: list error (stream=False with multiple URLs)
```
Error: "'list' object has no attribute 'status_code'"  
```
- Occurs when using deep crawl + `stream=False` + multiple URLs
- This is what user "@Daandeve" experienced in v0.8.0

### Root cause for both:
The `MemoryAdaptiveDispatcher` calls `crawler.arun()` for each URL, expecting a single `CrawlResult` object. However, when deep crawl is configured:
- `stream=True`: Deep crawl returns an **async generator**
- `stream=False`: Deep crawl returns a **list of CrawlResult** objects

The dispatcher then tries to access `.status_code` on these incompatible types, causing the errors.

## Root Cause Analysis

### Primary Cause:
The `MemoryAdaptiveDispatcher` cannot handle deep crawl strategy results when `stream=True`.

**Call flow:**
1. Docker API calls `crawler.arun_many()` with deep crawl config
2. Dispatcher's `crawl_url()` calls `crawler.arun(url, config)`
3. Deep crawl strategy returns **async generator** (not CrawlResult) when `stream=True`
4. Dispatcher tries to access `.status_code` on the async generator → **FAILS**

**Code locations:**
- `crawl4ai/async_dispatcher.py:687`: `result = await self.crawler.arun(url, config=selected_config)`
- `crawl4ai/async_dispatcher.py:692`: `if ... result.status_code:` (fails here)

### Why it works in non-streaming mode:
- `stream=False` → deep crawl returns `List[CrawlResult]` (awaited)
- `stream=True` → deep crawl returns `AsyncGenerator` (not awaited)

## Suggested Fixes

### Option 1: Fix in Dispatcher (Recommended)
Modify `crawl4ai/async_dispatcher.py` to handle both async generators and lists from deep crawl:

```python
# Around line 687 in crawl_url method
result = await self.crawler.arun(url, config=selected_config, session_id=task_id)

# Handle deep crawl streaming results (async generator)
if hasattr(result, '__aiter__'):
    try:
        result = await result.__anext__()
    except StopAsyncIteration:
        result = CrawlResult(url=url, html="", success=False, 
                           error_message="Deep crawl yielded no results")

# Handle deep crawl batch results (list)
elif isinstance(result, list):
    if len(result) > 0:
        result = result[0]  # Take first result, or could process all
    else:
        result = CrawlResult(url=url, html="", success=False,
                           error_message="Deep crawl returned empty list")
```

### Option 2: Fix in Docker API Handler
Modify `handle_stream_crawl_request()` in `deploy/docker/api.py` to process deep crawl separately.

**Comment by unclecode** [comment]
Thanks for the report! This is tracked in #1779 which covers Docker deep crawling issues. Closing to consolidate - please follow #1779 for updates.
