### ISSUE TITLE
[Bug]: Standard installation package includes torch and CUDA

### ISSUE THREAD

**Issue by betterthanever2** [unclecode/crawl4ai#1298]
### crawl4ai version

latest

### Expected Behavior

Size of installed package is reasonable

### Current Behavior

I'm using `crawl4ai[basic]` to use with a Docker-based instance. I built a new version yesterday, and the size of package went from ~150Mb to 3.3Gb. 
Removing `[basic]` resulted in the same behavior
Removing crawl4ai entirely reduced images size to normal

### Is this reproducible?

Yes

### Inputs Causing the Bug

```bash

```

### Steps to Reproduce

```bash

```

### Code snippets

```python

```

### OS

linux

### Python version

3.12

**Comment by aidnitra** [comment]
Same happened with me, @betterthanever2  btw can we connect or can you share your Dockerfile here which is producing lower image size. I am struggling to do so and stuck with 2.48GB of installation size.

Reverting to 0.6.3 for now as my image size exploding (it's still exploding btw).

I am expecting you are still using headless browser here and using probably ai features as well.

**Comment by betterthanever2** [comment]
@aidnitra I reverted to 6.0 version. The issue is not with Dockerfile, but with the c4ai package itself; it's something that should be fixed by the developers

**Comment by aidnitra** [comment]
> [@aidnitra](https://github.com/aidnitra) I reverted to 6.0 version. The issue is not with Dockerfile, but with the c4ai package itself; it's something that should be fixed by the developers

Would like to connect with you, I tried to build my docker image after using 0.6.0 version and I am using FastAPI server to expose it as a server, still can't figure out why image size is still not changing. Maybe you have pruned some files also which is not necessary.

**Comment by betterthanever2** [comment]
<img width="746" height="315" alt="Image" src="https://github.com/user-attachments/assets/74d5e182-a939-405a-a96e-5d1fb0f1f7c2" />

Here, in v0.13.18 I removed c4ai completely (to confirm that it's the c4ai that causes the issue). In v0.13.19 I pinned lib's version to 0.6.0.

Here's my Dockerfile, but be aware that it probably won't be very useful to you since it's pretty specific setup-wise:

```
# syntax=docker/dockerfile:1

ARG PYTHON_VERSION=3.12

FROM python:${PYTHON_VERSION}-slim-bullseye AS builder

RUN apt-get update \
    && apt-get install -y bash ncdu curl tar coreutils postgresql-client xz-utils openvpn \
    && curl -1sLf 'https://artifacts-cli.infisical.com/setup.deb.sh' | bash \
    && apt-get update \
    && apt-get install -y infisical \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN python -m pip install --no-cache-dir --upgrade pip

FROM builder AS final

ARG wheel=periodicals-0.13.19-py3-none-any.whl

COPY ./dist/$wheel .
RUN pip install --no-cache-dir --upgrade $wheel
```

**Comment by aadya940** [comment]
+1 , Hope to see this solved soon!

**Comment by jtha** [comment]
It's probably the addition of sentence-transformers causing this. @unclecode any way to make this optional? I understand it's required for the new features in 0.7, but it does increase the footprint significantly and not everyone might need/use the new features.

**Comment by t-anjan** [comment]
I am not upgrading to 0.7.x mainly because of this reason. The size of my containers became so large that the CI runners were getting killed when building the image itself.

**Comment by nomad2569** [comment]
> It's probably the addition of sentence-transformers causing this. [@unclecode](https://github.com/unclecode) any way to make this optional? I understand it's required for the new features in 0.7, but it does increase the footprint significantly and not everyone might need/use the new features.

+1

<img width="922" height="547" alt="Image" src="https://github.com/user-attachments/assets/195e3d7d-a103-4e85-91e9-6ce77c335310" />

⚠️ Significant Image Size Difference!
Especially in the amd64 image build, the size has increased nearly 10x due to the sentence-transformers → torch dependency.
If you don't need the features introduced in v0.7.0, I strongly recommend sticking with v0.6.3.

**Comment by aravindkarnam** [comment]
This has been fixed in the latest release 0.7.2. Read more about the dependancy optimisation in release note [here](https://github.com/unclecode/crawl4ai/releases/tag/v0.7.2)
