### ISSUE TITLE
[Bug]: JSON serialization error

### ISSUE THREAD

**Issue by jefcolbi** [unclecode/crawl4ai#1343]
### crawl4ai version

0.9.7

### Expected Behavior

I expect the crawler to informe me that the url doesn't have a valid web page.

### Current Behavior

Crawl4ai crash

### Is this reproducible?

Yes

### Inputs Causing the Bug

```bash
{
            "urls": ["https://avendre.yaknema.com/articles/1281/"],
            "crawler_params": {
                # Browser Configuration
                "headless": True,  # Run in headless mode
                "browser_type": "chromium",  # chromium/firefox/webkit

                # Performance & Behavior
                "page_timeout": 30000,  # Page load timeout (ms)
                "verbose": True,  # Enable detailed logging
                "semaphore_count": 5,  # Concurrent request limit

                # Anti-Detection Features
                "simulate_user": True,  # Simulate human behavior
                "magic": True,  # Advanced anti-detection
                "override_navigator": True,  # Override navigator properties
            }
        }
```

### Steps to Reproduce

```bash
Use python requests like this

 requests

requests.post("http://localhost:11235/crawl", json=[previous_input_data]])
```

### Code snippets

```python

```

### OS

Linux

### Python version

3.10.12

### Error logs & Screenshots (if applicable)

```python
ode context:
 758                               tag="GOTO",
 759                               params={"url": url},
 760                           )
 761                           response = None
 762                       else:
 763 →                         raise RuntimeError(f"Failed on navigating 
ACS-GOTO:\n{str(e)}")
 764   
 765                   await self.execute_hook(
 766                       "after_goto", page, context=context, url=url, 
response=response, config=config
 767                   )
 768    
2025-07-25 15:37:04,428 - api - INFO - Memory usage: Start: 124.671875 MB, End: 122.65234375 MB, Delta: -2.01953125 MB, Peak: 124.671875 MB
[2025-07-25 15:37:04 +0000] [13] [ERROR] Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.12/site-packages/starlette/_utils.py", line 77, in collapse_excgroups
  |     yield
  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 183, in __call__
  |     async with anyio.create_task_group() as task_group:
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 772, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    |     raise exc
    |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 182, in __call__
    |     with recv_stream, send_stream, collapse_excgroups():
    |                                    ^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    |     self.gen.throw(value)
    |   File "/usr/local/lib/python3.12/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    |     raise exc
    |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 184, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/app/server.py", line 169, in add_security_headers
    |     resp = await call_next(request)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    |     raise app_exc
    |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 144, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/usr/local/lib/python3.12/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 177, in __call__
    |     raise exc
    |   File "/usr/local/lib/python3.12/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 175, in __call__
    |     await self.app(scope, receive, send_wrapper)
    |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 716, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 736, in app
    |     await route.handle(scope, receive, send)
    |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 290, in handle
    |     await self.app(scope, receive, send)
    |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 78, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 75, in app
    |     response = await f(request)
    |                ^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 302, in app
    |     raw_response = await run_endpoint_function(
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
    |     return await dependant.call(**values)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/slowapi/extension.py", line 734, in async_wrapper
    |     response = await func(*args, **kwargs)  # type: ignore
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/app/server.py", line 446, in crawl
    |     return JSONResponse(res)
    |            ^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/starlette/responses.py", line 190, in __init__
    |     super().__init__(content, status_code, headers, media_type, background)
    |   File "/usr/local/lib/python3.12/site-packages/starlette/responses.py", line 47, in __init__
    |     self.body = self.render(content)
    |                 ^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/starlette/responses.py", line 193, in render
    |     return json.dumps(
    |            ^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    |     **kw).encode(obj)
    |           ^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    |     chunks = self.iterencode(o, _one_shot=True)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    |     return _iterencode(o, 0)
    |            ^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    |     raise TypeError(f'Object of type {o.__class__.__name__} '
    | TypeError: Object of type property is not JSON serializable
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
                                   ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/local/lib/python3.12/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/server.py", line 169, in add_security_headers
    resp = await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    raise app_exc
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.12/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 177, in __call__
    raise exc
  File "/usr/local/lib/python3.12/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 175, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 75, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 302, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/slowapi/extension.py", line 734, in async_wrapper
    response = await func(*args, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/server.py", line 446, in crawl
    return JSONResponse(res)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/starlette/responses.py", line 190, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "/usr/local/lib/python3.12/site-packages/starlette/responses.py", line 47, in __init__
    self.body = self.render(content)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/starlette/responses.py", line 193, in render
    return json.dumps(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type property is not JSON serializable
```

**Comment by dandzem** [comment]
Same issue started to happen after `0.7.2 ` Release. 

Error happening on websites, that previously were successfully parsed.

Tried to rollback to `unclecode/crawl4ai:test-0.7.1` docker version, but error still persist.

Tried to update python package to latest version, but still same error

`TypeError: Object of type property is not JSON serializable`

**Comment by ntohidi** [comment]
@jefcolbi @dandzem 
Hi everyone. The bug and the error message provided have been fixed in the latest version of the Docker image. Could you please check the latest version?

**Comment by TideDra** [comment]
> [@jefcolbi](https://github.com/jefcolbi) [@dandzem](https://github.com/dandzem) Hi everyone. The bug and the error message provided have been fixed in the latest version of the Docker image. Could you please check the latest version?

docker built from latest code still gets this error: `Object of type property is not JSON serializable`. Maybe we need to merge this PR #1356

**Comment by notfoundry** [comment]
I'm still seeing this exact same issue, with the exact same traceback, on the latest release. Doesn't seem to have been resolved by the fix

**Comment by ntohidi** [comment]
> > [@jefcolbi](https://github.com/jefcolbi) [@dandzem](https://github.com/dandzem) Hi everyone. The bug and the error message provided have been fixed in the latest version of the Docker image. Could you please check the latest version?
> 
> docker built from latest code still gets this error: `Object of type property is not JSON serializable`. Maybe we need to merge this PR [#1356](https://github.com/unclecode/crawl4ai/pull/1356)

Yeah, we have implemented the idea in the PR. it's in the `develop` branch. we will inclode it in our next release soon.

**Comment by narenmanoharan** [comment]
@ntohidi any update on the release?

**Comment by ntohidi** [comment]
@narenmanoharan It's fixed in the develop branch, and hopefully, it will be included in the next release next week.

**Comment by healer156** [comment]
> [@narenmanoharan](https://github.com/narenmanoharan) It's fixed in the develop branch, and hopefully, it will be included in the next release next week.

docker image versions(0.7.4、0.7.3) are still not work for this issue...

**Comment by ntohidi** [comment]
> > [@narenmanoharan](https://github.com/narenmanoharan) It's fixed in the develop branch, and hopefully, it will be included in the next release next week.
> 
> docker image versions(0.7.4、0.7.3) are still not work for this issue...

yes, we will update the Docker image soon

**Comment by astappiev** [comment]
What version is the last working? I built a Docker image from `develop`, but it's still broken.

**Comment by astappiev** [comment]
[0.6.0-r2](https://hub.docker.com/layers/unclecode/crawl4ai/0.6.0-r2/images/sha256-fc4281eb34cdcd314b455768c1a9dd8490a1662a90ef4d01ff5be51ec4edbb16) seems to work

**Comment by healer156** [comment]
> [0.6.0-r2](https://hub.docker.com/layers/unclecode/crawl4ai/0.6.0-r2/images/sha256-fc4281eb34cdcd314b455768c1a9dd8490a1662a90ef4d01ff5be51ec4edbb16) seems to work

But 0.6.0-r2 has another error , ERR_INVALID_AUTH_CREDENTIALS ,it looks like proxy setting  is not work

**Comment by yvesloy** [comment]
@ntohidi would be great to get this soon!!

**Comment by ntohidi** [comment]
Fixed in the newest release, 0.7.6. Please pull the latest image

**Comment by HeirloomForge** [comment]
pulled latest and still getting this error.  successful extract but failed to send.
```
[FETCH]... ↓ https://heirloomforge.com/blog                                     

| ✓ | ⏱: 2.58s 

[SCRAPE].. ◆ https://heirloomforge.com/blog                                     

| ✓ | ⏱: 0.02s 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new

LiteLLM.Info: If you need to debug this error, use `litellm._turn_on_debug()'.

[EXTRACT]. ■ https://heirloomforge.com/blog                                     

| ✓ | ⏱: 0.30s 

[COMPLETE] ● https://heirloomforge.com/blog                                     

| ✓ | ⏱: 2.90s 

[2025-10-29 15:57:52 +0000] [13] [ERROR] Exception in ASGI application

  + Exception Group Traceback (most recent call last):

  |   File "/usr/local/lib/python3.12/site-packages/starlette/_utils.py", line 79, in collapse_excgroups

  |     yield

  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 183, in __call__

  |     async with anyio.create_task_group() as task_group:

  |                ^^^^^^^^^^^^^^^^^^^^^^^^^

  |   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 772, in __aexit__

  |     raise BaseExceptionGroup(

  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)

  +-[+-------------](dialpad://%2B-------------)--- 1 ----------------

    | Traceback (most recent call last):

    |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi

    |     result = await app(  # type: ignore[func-returns-value]

    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__

    |     return await self.app(scope, receive, send)

    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1133, in __call__

    |     await super().__call__(scope, receive, send)

    |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__

    |     await self.middleware_stack(scope, receive, send)

    |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__

    |     raise exc

    |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__

    |     await self.app(scope, receive, _send)

    |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 182, in __call__

    |     with recv_stream, send_stream, collapse_excgroups():

    |                                    ^^^^^^^^^^^^^^^^^^^^

    |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    |     self.gen.throw(value)

    |   File "/usr/local/lib/python3.12/site-packages/starlette/_utils.py", line 85, in collapse_excgroups

    |     raise exc

    |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__

    |     await response(scope, wrapped_receive, send)

    |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 223, in __call__

    |     async for chunk in self.body_iterator:

    |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 169, in body_stream

    |     assert message["type"] == "http.response.body", f"Unexpected message: {message}"

    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    | AssertionError: Unexpected message: {'type': 'http.response.start', 'status': 200, 'headers': [(b'content-length', b'4'), (b'content-type', b'application/json')]}

    [+-------------](dialpad://%2B-------------)-----------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__

    return await self.app(scope, receive, send)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1133, in __call__

    await super().__call__(scope, receive, send)

  File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__

    raise exc

  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__

    await self.app(scope, receive, _send)

  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 182, in __call__

    with recv_stream, send_stream, collapse_excgroups():

                                   ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__

    self.gen.throw(value)

  File "/usr/local/lib/python3.12/site-packages/starlette/_utils.py", line 85, in collapse_excgroups

    raise exc

  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__

    await response(scope, wrapped_receive, send)

  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 223, in __call__

    async for chunk in self.body_iterator:

  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 169, in body_stream

    assert message["type"] == "http.response.body", f"Unexpected message: {message}"

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AssertionError: Unexpected message: {'type': 'http.response.start', 'status': 200, 'headers': [(b'content-length', b'4'), (b'content-type', b'application/json')]}
```
