### ISSUE TITLE
Unexpected error happened when crawling a website with too long url

### ISSUE THREAD

**Issue by PhuongBui712** [unclecode/crawl4ai#22]
Hi guys,

First, I want to appreciate your effort to create a helpful python package which helps develop RAG much easier.

However, I've met an error when I tried your package and I think it's unexpected. I've figured out (incrawler_strategy.py) in your crawling 
strategy, you cached the page source in a temporary file by its URL like following:

![Uploading Screenshot 2024-06-15 at 11.13.22.png](crawler_strategy.py)

But sometimes, the URL is too long and it may cause an error when stored in disk. I propose another way to cache the file such as a random name and k-v dictionary to keep touch URL with the associated cache file

**Comment by unclecode** [comment]
@PhuongBui712 you are very welcome, unfortunately I can't see your screenshot, would you share an example of URL caused such issue? Then I will work on it right away

**Comment by PhuongBui712** [comment]
Thanks for replying. I am sorry about my screenshot. Here is the example [notebook](https://colab.research.google.com/drive/1htbdOK0_Pva9OIybEl52s6HSWNNFWLjf?usp=sharing) about the problem I said. The URL I used is actually a clean URL but it's longer because of encoding/decoding URL.

**Comment by unclecode** [comment]
@PhuongBui712 Thanks for sharing. The issue is resolved; please update to 0.2.4. Great job reporting this, very helpful.

**Comment by unclecode** [comment]
@PhuongBui712 Please remove public access to your Colab and don't keep your GROQ API token there. It's better to remove it and create a new one. That's why I hid your comment, to avoid misuse.

**Comment by PhuongBui712** [comment]
Thanks a lot! I've already checked it before sharing but I don't know how it's still appeared.
