### ISSUE TITLE
[Bug]: arun_many error when using BFSDeepCrawlingStrategy

### ISSUE THREAD

**Issue by egianetto** [unclecode/crawl4ai#940]
### crawl4ai version

0.5.0.post8

### Expected Behavior

As far as I understand, arun_many() should work with any strategy.
I've tested, and when running with default strategy, it works.

### Current Behavior

But when I add a deep_crawl_strategy=BFSDeepCrawlStrategy, then it throws the error:
Error Message:  'async_generator' object has no attribute 'status_code'

### Is this reproducible?

Yes

### Inputs Causing the Bug

```bash

```

### Steps to Reproduce

```bash
To see the expected behaviour, run: python arun_many_bug.py

Then to see the error, run: python arun_many_bug.py bfs
```

### Code snippets

```python
import asyncio

from crawl4ai import (
    AsyncWebCrawler,
    CrawlerRunConfig,
    BFSDeepCrawlStrategy,
    CacheMode,
)

async def basic_deep_crawl(bfs: bool = False):

    if bfs:
        print('-- BFS config --')
        config = CrawlerRunConfig(
            deep_crawl_strategy=BFSDeepCrawlStrategy(
                max_depth=1,
                max_pages=2,
                include_external=False,

            ),
            cache_mode=CacheMode.BYPASS,
            stream=True,
        )
    else:
        print('-- Default config --')
        config = CrawlerRunConfig(
            cache_mode=CacheMode.BYPASS,
            stream=True,
        )

    async with AsyncWebCrawler() as crawler:

        async for result in await crawler.arun_many(urls=['https://crawl4ai.com'], config=config):
            print('len(HTML): ', len(result.html))
            print('Success: ', result.success)
            print('Error Message: ', result.error_message)


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == 'bfs':
        asyncio.run(basic_deep_crawl(True))
    else:
        asyncio.run(basic_deep_crawl(False))
```

### OS

macOS

### Python version

3.12.4

### Error logs & Screenshots (if applicable)

When running with default strategy:

<img width="552" alt="Image" src="https://github.com/user-attachments/assets/86bdf524-cff0-486b-a5c3-448c6772346e" />

When running with BFSDeepCrawlStrategy:

<img width="574" alt="Image" src="https://github.com/user-attachments/assets/c5bff7b7-53f9-46ee-bc6e-70135ea97097" />

**Comment by ntohidi** [comment]
Hi @egianetto
Thanks for the heads-up!  Just a quick note, we’ve already fixed this bug in the `next` branch.

**Comment by DongDong20050214** [comment]
> Hi [@egianetto](https://github.com/egianetto) Thanks for the heads-up! Just a quick note, we’ve already fixed this bug in the branch.`next`

good,I just was confused with zhis

**Comment by Brenndoerfer** [comment]
This is not fixed on 0.6.2 nor on the next branch (installed via `pip install git+https://github.com/unclecode/crawl4ai.git@next`) 

Still getting `'async_generator' object has no attribute 'status_code'` when using a `deep_crawl_strategy` with `arun_many`

**Comment by greatwitenorth** [comment]
I'm also still seeing this error in v0.6.2

**Comment by DevJake** [comment]
I'm also seeing this on `v0.6.2`. Looks like Crawl4AI could do with some unit tests and CI/CD pipelines. I'd be happy to help build some!

**Comment by ntohidi** [comment]
yes, I can confirm that it's still happening in 0.6.3. i will open the issue @aravindkarnam

**Comment by peterkostadinov** [comment]
See https://github.com/unclecode/crawl4ai/issues/1205 for details on the issue.

**Comment by 928871247** [comment]
I'm also still seeing this error in v0.7.6.

**Comment by unclecode** [comment]
Thanks for the report! This has been fixed on the develop branch and will be included in the next release.
